# Site settings
title: Service Analytics Evidence Base
email: your-email@domain.com
url: https://s-laugh.github.io/saeb/
description: "To create a solution that integrates data, making it available and reusable in real-time for the purposes of planning, performance, reporting, and/or service improvement through analytics, across channels and programs."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#666'
  links: '#219ab3'

# Footer settings
footer: Her Majesty the Queen in Right of Canada, as represented by the Employment and Social Development Canada

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
