# Site settings
title: Service Analytics Evidence Base
email: 
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/saeb/" # the subpath of your site, e.g. /blog/
url: "s-laugh.github.io" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
